language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

# Use container-based infrastructure
sudo: false

install:
  - pip install .

script: python vokativ/tests/all.py

branches:
  only:
    - master
