language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install .
script: python vokativ/tests/all.py
branches:
  only:
    - master
